# Generated by Django 5.1.6 on 2025-03-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_message_deleted_for_message_edited_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_content',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
